### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by jodastephen** [pithu/js-joda#1]
I generally consider the "joda" name at the start of a project name to be restricted to projects directly associated with me (the author of Joda-Time). When ported to other languages, developers traditionally vary the name, eg "Noda-Time" on .NET or "Soda-Time" on Scala. Thus "JS-Joda-Time" would be OK by me, although you may want to consider alternatives.

In addition, since you are porting JSR-310, rather than Joda-Time, it might be worth naming after the "threeten" name, such as "JS-ThreeTen".

**Comment by pithu** [comment]
Dear Stephen, thank you very much for your input, i set great value upon your opinion. 
Even if we are porting to JSR-310, i prefer a name after joda, because i guess a name after the good old "java specification world" will be quite unpopular in the javascript community.  
Unfortunately javascript starts with the same letter as java, so for now i take your proposal "js-joda-time" until we find a better alternative.

**Comment by pithu** [comment]
finally choose the name js-joda. i hope your fine with that

**Comment by jodastephen** [comment]
I have no problems with that name.
